
export interface VirtualFile {
  path: string; // Relative path, e.g., "src/components/Button.tsx"
  name: string;
  content: string | Uint8Array | File; // File object allows lazy loading
  size: number; // Store size explicitly
  type: 'file' | 'directory';
  lastModified: number;
  mimeType?: string;
}

export enum ActionType {
  READ = 'read',
  WRITE = 'write',
  APPEND = 'append',
  MOVE = 'move',
  DELETE = 'delete',
  MKDIR = 'mkdir',
  GENERATE_IMAGE = 'generate_image',
  EDIT_IMAGE = 'edit_image',
  COMPOSE_IMAGE = 'compose_image',
  CALCULATE_MATH = 'calculate_math',
  GENERATE_VIDEO = 'generate_video',
  TRIM_VIDEO = 'trim_video',
  RUN_SCRIPT = 'run_script',
  GOOGLE_SEARCH = 'google_search'
}

export interface AgentAction {
  id: string;
  type: ActionType;
  path: string;
  content?: string; // For write/append/generate_image (prompt)
  source_path?: string; // For move or edit_image
  source_paths?: string[]; // For compose_image (multiple inputs)
  description?: string;
  start_time?: number; // Start time in seconds for trimming
  end_time?: number; // End time in seconds for trimming
}

export interface RiskAssessment {
  has_destructive_actions: boolean;
  confirmation_required_ids: string[];
}

export interface AgentResponse {
  thought: string;
  final_answer?: string; // For direct answers (math, logic)
  plan: string[];
  risk_assessment: RiskAssessment;
  actions: AgentAction[];
  raw?: string; // Raw output from model for debugging/streaming feedback
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string; // User prompt or raw text
  agentResponse?: AgentResponse; // Parsed JSON from model
  timestamp: number;
  attachments?: VirtualFile[]; // Files uploaded with this message
  isObservation?: boolean; // If true, this is a system/tool output message
  isError?: boolean;
}

export enum ModelId {
  GEMINI_3_PRO = 'gemini-3-pro-preview',
  GEMINI_3_FLASH = 'gemini-3-flash-preview',
  GEMINI_2_5_FLASH = 'gemini-2.5-flash',
  GEMINI_2_5_FLASH_LITE = 'gemini-2.5-flash-lite',
  GEMINI_ROBOTICS = 'gemini-robotics-er-1.5-preview'
}

export type Language = 'zh' | 'en';

export const UI_TEXT = {
  zh: {
    appName: '暗黑AGI',
    brandSuffix: '&深度之眼',
    workspace: '工作区',
    files: '文件',
    noFiles: '暂无文件',
    uploadHint: '上传文件或让智能体创建',
    thoughtProcess: '思考过程',
    finalAnswer: '最终答案',
    executedActions: '执行动作',
    enterCommand: '输入指令...',
    initializeTitle: '暗黑AGI',
    initializeDesc: '由 Gemini 3.0 驱动的通用智能体。支持多模态分析、自主编程、联网搜索及文件系统深度操作。',
    processing: 'AGI 正在运行...',
    systemObservation: '系统观察',
    systemError: '系统错误',
    resetSession: '重置会话',
    model: '模型',
    previewLoading: '正在加载预览...',
    previewTooLarge: '文件太大无法预览 (>10MB)。请下载查看。',
    previewBinary: '[二进制内容]',
    previewError: '[加载预览出错]',
    download: '下载',
    close: '关闭',
    version: 'V2.4',
    stop: '停止',
    stopped: '已中止',
    rawOutput: '原始输出日志',
    rawOutputDesc: '模型生成的原始数据流'
  },
  en: {
    appName: 'Dark AGI',
    brandSuffix: '&DeepShare',
    workspace: 'WORKSPACE',
    files: 'files',
    noFiles: 'No files.',
    uploadHint: 'Upload files or ask Agent to create them.',
    thoughtProcess: 'Thought Process',
    finalAnswer: 'Final Answer',
    executedActions: 'Executed Actions',
    enterCommand: 'Enter your command...',
    initializeTitle: 'Dark AGI',
    initializeDesc: 'Powered by Gemini 3.0. A multimodal autonomous agent capable of coding, searching, media processing, and complex reasoning.',
    processing: 'AGI IS RUNNING...',
    systemObservation: 'SYSTEM_OBSERVATION',
    systemError: 'SYSTEM_ERROR',
    resetSession: 'Reset Session',
    model: 'Model',
    previewLoading: 'Loading preview...',
    previewTooLarge: '[File too large for preview (>10MB). Please download to view.]',
    previewBinary: '[Binary Content]',
    previewError: '[Error loading preview]',
    download: 'Download',
    close: 'Close',
    version: 'V2.4',
    stop: 'Stop',
    stopped: 'Stopped',
    rawOutput: 'Raw Output Log',
    rawOutputDesc: 'Raw data stream generated by the model'
  }
};
